# Generated by Django 6.0.6 on 2026-06-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("complaint_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("status", models.CharField(default="Submitted", max_length=50)),
            ],
        ),
    ]
