# Generated by Django 6.0.6 on 2026-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_complaint_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="latitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="longitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
