# Generated by Django 6.0.6 on 2026-06-23 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_complaint_latitude_complaint_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
